version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env.db
  redis:
    image: redis:7.0.7
    ports:
      - 6379:6379
volumes:
  postgres_data:
