name: tests

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: cp src/tests/functional/.env.tests.example src/tests/functional/.env.tests && docker-compose -f src/tests/functional/docker-compose.tests.yml up --build tests
